### ISSUE TITLE
Missing Modules

### ISSUE THREAD

**Issue by anirudhjoshi** [ThQ/p8ste#1]
I've downloaded pygments, no errors there.

Import errors - no modules (missing):
paste.private
recaptcha.client.captcha

From file: src/page/pasties/add/**init**.py

**Comment by ThQ** [comment]
I've just pushed a new version that makes it easier to check if everything is ready to run. If you're on linux just run :
cd path/to/paste-it/ && make check-install

Basically you need to create a src/paste/private.py (rename src/paste/private_TEMPLATE.py : only present in the latest push) and extract http://pypi.python.org/pypi/recaptcha-client to src/recaptcha.

Tell me if that's OK for you.

**Comment by anirudhjoshi** [comment]
No import errors now.
