### ISSUE TITLE
Recaptcha when submitting fails to accept

### ISSUE THREAD

**Issue by anirudhjoshi** [ThQ/p8ste#2]
Trying to paste some code, and entering the right captcha asks - Please try again.

When submitting sometimes the link is created; but as captcha returns false you end up with:

The page /HsQbuwl was not found on our server. You may have followed a bad link or mistyped the URL.

**Comment by ThQ** [comment]
This is because your recaptcha private api key is invalid (see src/paste/private.py), sign in and it should be fine (no recaptcha question).

Strange though that it creates the paste when the captcha answer is incorrect. Can't get it to do that here. I'll try again.

**Comment by anirudhjoshi** [comment]
Replaced "YOUR KEY HERE" in src/paste/private.py - with my private recaptcha global key (all domains) - same recaptcha error.

Ignore the creation of extraneous paste, might be from latent datastore storage of your paste-it version pasties I got from google code svn.

**Comment by ThQ** [comment]
I can't get recaptcha-client to give ANY information about what failed about an answer (bad answer or bad key ?).

But I can tell you that I use a global key too. Does your key work elsewhere ?

**Comment by anirudhjoshi** [comment]
paste/private.py -> 

config["recaptcha::key::private"] = "PRIVATE KEY HERE"

paste/**init**.py ->

config["recaptcha::key::public"] = "PUBLIC KEY HERE"

I grep'ped for that, it works now XD. Perhaps put in the readme.

**Comment by ThQ** [comment]
Great, thanks.

I've pushed a README : http://github.com/thomas-quemard/p8ste/blob/master/README.markdown
