### ISSUE TITLE
It doesn't find any module, using latest push.

### ISSUE THREAD

**Issue by hhsajjad** [ThQ/p8ste#5]
Dude, whenever I run 'make check-install', it never succeeds. It never finds a module. I'm greatly new into this stuff, and using Linux, so please can you send me the copy of WORKING project? I put every module but nothing gets found. 

By the way, here is the DIRECTORY LIST of my project folder. Please check and tell what am I doing wrong! :(
http://www.mediafire.com/?d6f80kg94vhkp8g (TXT file, 706KB)

PLEASE PLEASE HELP ME.. OR SEND ME THE WORKING PROJECT FOLDER... PLEEASE.. I'M DYING FOR IT, I SWEAR..

Email, if needed: bott@live.com

**Comment by hhsajjad** [comment]
Okay Feedparser and Pygments installed. But what the hell is with poor reCAPTCHA?

**Comment by hhsajjad** [comment]
Okay, I figured it out. Its working now. But..
"Don't forget to check `src/paste/__init__.py` and `src/paste/private.py"

Where is the 'paste' directory? I'm not having any. And yeah, why do our site looks different from paste-it.appspot.com??

**Comment by hhsajjad** [comment]
Paste-It.Appspot.com looks pretty amazing, and ours look like text-only.. why? Can't we have like yours? :/

**Comment by hhsajjad** [comment]
Can you make me admin of your project on AppEngine so I can download the code.. Hmmm?

**Comment by ThQ** [comment]
[Just removed the useless line](https://github.com/thomas-quemard/p8ste/commit/a2d5d88d45e2cced7d47b0c5ecf1e984e2c7405c) in the README. Thanks.

The repo does not contain images, you're right. I've just uploaded an archive with them though :
https://github.com/downloads/thomas-quemard/p8ste/p8ste_images.tar.gz

**Comment by hhsajjad** [comment]
Hey! Thanks alot. 
I'm gonna try it tonight. Thanks alot again for the images. Hold your breath till I return.. ;-)

**Comment by hhsajjad** [comment]
Dear, I can't put Feedparser because it alone has 4k+ files and maximum we can have are 3k. What should I do? I tried uploading without that folder and receiving error: <type 'exceptions.ImportError'>: No module named feedparser

Please reply me..

**Comment by ThQ** [comment]
You only need to put feedparser.py into libs, not the whole doc and all.

**Comment by hhsajjad** [comment]
Aww! Thanks alot.. I'll reply back and close the topic on as needed basis :)

**Comment by ThQ** [comment]
I'm clossing this issue. Open another one if you have any more trouble.

**Comment by ThQ** [comment]
I've just commited a shell script to install python dependencies, just run `make install-python-dependecies`.
